services:
  searxng:
    image: searxng/searxng:latest
    container_name: golligog-searxng
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./searxng-config:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://localhost:8080/
      - SEARXNG_SECRET_KEY=your-secret-key-change-in-production
    networks:
      - searxng-net
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: golligog-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - searxng-net

volumes:
  redis-data:
    driver: local

networks:
  searxng-net:
    driver: bridge